# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.delete_all
Afiliation.delete_all
Character.delete_all
Favorite.delete_all

paul = User.create(name: "paul", username: "paul", password: "password", email: "paul")
gair = User.create(name: "gair", username: "gair", password: "password", email: "gair")

thundercats = Afiliation.create(name: "Thundercats")
lunataks = Afiliation.create(name: "Lunataks")
mutants = Afiliation.create(name: "Mutant")

@lion_o = Character.create(name: "Lion-O", gender: "male", weapons: "Sword of Omens, Claw Shield and Red Cloak", species: "Thunderian", overview: "The hereditary Lord of the ThunderCats, Lion-O is the son of Claudus, the ruler of Thundera at the time of its destruction. Initially a boy stuck in a man’s body, the years saw Lion-O develop the wisdom and skills needed to lead the ThunderCats on Third Earth, and later lead the rebuilding of his home world of New Thundera. Lion-O can be quick to anger, and is impulsive and headstrong, but also possesses great moral values, at the forefront of those being the Code of Thundera – Justice, Truth, Honour, and Loyalty. Lion-O is fierce defender of freedom and a brave and noble leader, one that the other ThunderCats are proud to stand beside.", favorite: false, afiliation: thundercats)

@tygra = Character.create(name: "Tygra", gender: "male", weapons: "Bolo Whip", species:"Thunderian", overview: "Tygra is the architect of Cats Lair, a highly intelligent and thoughtful ThunderCat whose primary strengths are his mental abilities. Perhaps because of his experience and knowledge, along with his levelheaded nature, even though Lion-O is Lord of the ThunderCats, Jaga appointed Tygra as the Head of the ThunderCats Council. Although naturally shy and peaceable in personality, Tygra is nonetheless a formidable adversary in combat and will never shy away from battle in the defence of his friends or the innocent.", favorite: false, afiliation: thundercats)

@pantrho = Character.create(name: "Pantrho", gender: "male", weapons: "Fighting sticks, usually referred to as nunchukus", species: "Thunderian", overview: "Panthro is unquestionably the most naturally aggressive of the ThunderCats. Although never one to pick a fight, Panthro is never afraid of battle – whilst this can lead to him being quite headstrong, Panthro’s get-up-and-go, never-say-die personality can also serve as a great motivator for the others. Conversely, mixed in with Panthro’s warrior ways is a kindness and compassion that provides the perfect balance to his personality. Panthro is happiest tinkering with machinery, and has an almost paternal affection for the Thundertank, of which he is very protective and which he regularly refers to as his “baby”! A warrior in the truest sense of the world, Panthro is always a force to be reckoned with.", favorite: false, afiliation: thundercats)

@heetara= Character.create(name: "Cheetara", gender: "female", weapons: "Staff", species: "Thunderian", overview: "A captivating mixture of feminine beauty and gentility coupled with athleticism and the fighting skill of her male comrades, Cheetara has served many roles in the ThunderCat team – her relationship to Lion-O has evolved from being a maternal, almost mother-like figure to being an equal and advisor in times of need, and the others all look to her for the intuition and insight she is able to bring to a situation. Gentle but tough, Cheetara is no damsel-in-distress, often proving a pivotal figure in the downfall of the ThunderCats’ enemies, and is unquestionably regarded as a true equal to the other ThunderCats.", favorite: false, afiliation: thundercats)

@wilykat = Character.create(name: "Wilykat", gender: "male", weapons: "Utility belt: Special pellets (e.g., smoke pellets and other trick pellets) and lasso.", species: "Thunderian", overview: "Accurately described as a “cunning junior duo”, the Thunderkittens are small in size and still maturing, yet still serve a vital role in the ThunderCat ranks. Inseparable despite their competitive natures, both WilyKat and WilyKit are impatient to grow up and take their place amongst the adult ThunderCats. Inquisitive and impetuous, the Thunderkittens have been known to stir up their fair share of problems for the others to deal with, but with their good consciences and brave spirits they can always be relied upon to do the right thing in the end.", favorite: false, afiliation: thundercats)

@wilykit = Character.create(name: "Wilykit", gender: "feamle", weapons: "Utility belt: Special pellets (e.g., smoke pellets and other trick pellets) and lasso.", species: "Thunderian", overview: "Accurately described as a “cunning junior duo”, the Thunderkittens are small in size and still maturing, yet still serve a vital role in the ThunderCat ranks. Inseparable despite their competitive natures, both WilyKat and WilyKit are impatient to grow up and take their place amongst the adult ThunderCats. Inquisitive and impetuous, the Thunderkittens have been known to stir up their fair share of problems for the others to deal with, but with their good consciences and brave spirits they can always be relied upon to do the right thing in the end.", favorite: false, afiliation: thundercats)

@lynx_o = Character.create(name: "Lynx-O", gender: "male", weapons: "Light Shield and Braille Board", species: "Thunderian", overview: "The oldest and wisest of the “new” ThunderCats, all of the ThunderCats look to Lynx-O for insight into the many perilous situations they encounter. Possessed of a great clarity of vision, Lynx-O uses his blindness almost to his advantage, his lack of sight enabling him to always look beneath the surface for a situation’s inner truth. Lynx-O’s calm, rational personality provides the perfect counterpoint to Pumyra and Bengali’s more rash, youthful temperaments, and as such he is very much the vital link within their team.", favorite: false, afiliation: thundercats)

@bengali = Character.create(name: "Bengali", gender: "male", weapons: "The Hammer of Thundera", species: "Thunderian", overview: "One of the three Thunderian survivors anointed to the rank of ThunderCat, Bengali is the youngest of the group, and is thus slightly more hot-headed and combative than his two comrades Lynx-O and Pumyra. Bengali is the younger brother of Tygra, and although he lacks some of his brother’s knowledge and wisdom, as a fighter he is the equal of his elder sibling, possessed of a strong heart, courage and seemingly endless resourcefulness.", favorite: false, afiliation: thundercats)

@pumyra = Character.create(name: "Pumyra", gender: "female", weapons: "Sling", species: "Thunderian", overview: "Another of the three Thunderians to reach Third Earth following their home planet’s destruction, Pumyra in many ways is like a younger version of Cheetara, possessed of a feminine nature that belies a flair for combat. Like the other “new” ThunderCats, Pumyra had to learn to be resourceful in order to survive the potentially hostile environs of Third Earth, and in so doing truly earned her place amongst the elite Thunderians known as the ThunderCats.", favorite: false, afiliation: thundercats)

@snarf = Character.create(name: "Snarf", gender: "male", weapons: "None", species: "Snarfs", overview: "Entrusted with the care of the young Lion-O, Snarf Osbert (known simply as “Snarf” to his fellow ThunderCats) often thinks of himself as the oldest member of the group, at least barring Lynx-O and Jaga. Although Snarf is an excessive worrier and something of a pessimist, his courage is as strong as the other, full-sized ThunderCats, particularly when defending Lion-O, of whom Snarf is somewhat over-protective. Snarf can be slightly absent-minded and bumbling, perhaps due to his advancing years, but can always be called upon to ably aid the ThunderCats whenever he is needed.", favorite: false, afiliation: thundercats)

@mumm_ra = Character.create(name: "Mumm-ra", gender: "male", weapons: "Sword of Plun-Darr", species:"Unknown", overview: "Mumm-Ra the Everliving, evil devil priest of Third Earth, has lived for centuries, since the planet was known as First Earth. With his loyal hound Ma-Mutt, Mumm-Ra was the source of all evil on the planet, residing within his black pyramid and drawing vast amounts of power from The Ancient Spirits of Evil. Mumm-Ra’s decayed form could be transformed into that of Mumm-Ra the Everliving by a chant which went ‘Ancient Spirits of Evil, transform this decayed form to Mumm-Ra the Everliving!’ In his Everliving form Mumm-Ra became even more powerful, but was forced to return to his sarcophagus within his pyramid and rest after a time. Mumm-Ra’s greatest weakness however, was that he could not stand to see his own reflection, and look upon all his evil.", favorite: false, afiliation: mutants)

@slithe = Character.create(name: "S-S-Slithe", gender: "male", weapons: "Axe, mace and warp gas", species: "Mutant", overview: "The self-appointed leader of the Mutants stranded on Third Earth, S-S-Slithe is the embodiment of all that is evil about that Plun-Darrian race – ruthless, cunning, cruel and totally without remorse, S-S-Slithe craves the power of the Eye of Thundera and will let nothing stand between him and it. One of the more perceptive and intelligent Mutants, one of S-S-Slithe’s greatest weaknesses is his overconfidence and ruthless ambition, coupled with a traitorous nature, all traits exploited by the devil priest Mumm-Ra in his efforts to recruit the Mutants as willing vessels of his own lust for power.", favorite: false, afiliation: mutants)

@jackalman = Character.create(name: "Jackalman", gender: "male", weapons: "Club and Axe", species: "Mutant", overview: "Cruel, cunning, cowardly and driven by ambition, Jackalman grudgingly serves under the leadership of S-S-Slithe in the hope of one day seizing ultimate power for himself. Like all the Mutants, Jackalman is loyal only to himself – initially easily impressed by the grandiose leadership style of S-S-Slithe, Jackalman’s loyalty to the Reptillian leader gradually waned over the course of their many defeats at the hands of the ThunderCats. More intelligent than Monkian, but hampered by his cowardly nature, Jackalman’s lust for power is rivalled only by his hatred of the Mutants’ sworn enemies, the ThunderCats and their friends.", favorite: false, afiliation: mutants)

@monkian = Character.create(name: "Monkian", gender: "male", weapons: "Spiked mace, spiked ball and chain and boulder-shooting shield", species: "Mutant", overview: "One of the original three Mutants to find themselves stranded on Third Earth, Monkian is true to his name – a powerful warrior, Monkian is at his best and most deadly in the treetops, where his agile climbing and swinging ability is able to come to the fore. Because of his more ape-like tendencies, Monkian’s treetop skill is matched by a natural aggression, and this selfsame aggression causes Monkian to possess a lower level of intelligence than the other Mutants, which in turn causes them to look down on him. However, Monkian is nonetheless as ambitious and ruthless as his cohorts, and both allies and foes would underestimate him at their peril.", favorite: false, afiliation: mutants)

@vultureman = Character.create(name: "Vultureman", gender: "male", weapons: "Net Capture Gun", species: "Mutant", overview: "In many ways the brains behind the Mutant operation, Vultureman’s skill with all things electrical, mechanical and chemical marks him out as the most intelligent of the Mutants, and consequently the most ambitious. Although happiest attempting to defeat the ThunderCats with brains rather than brawn, Vultureman is still not averse to using directly offensive means to strike at his enemies, and is perhaps most dangerous behind the cockpit of his Flying Machine. Scorned by his fellow Mutants, about whom he has regularly expressed dissatisfaction, Vultureman’s ambitious nature is evident by the number of times he has broken ranks with the Mutants, either going solo or joining up with the ThunderCats’ other Plun-Darrian nemeses, the Lunataks.", favorite: false, afiliation: mutants)

@ratar_o = Character.create(name: "Ratar-o", gender: "male", weapons: "Rat’s Eyes (daggers)", species: "Mutant", overview: "An arrogant and domineering leader, Ratar-O visualises himself as an expert Mutant commander and military strategist, able to employ the right balance of brainpower and brute force to defeat his enemies. In reality Ratar-O is one of the ThunderCats’ deadliest foes, but, like many of the Mutants, is undermined by his overconfidence and an inability to in any way endear himself to those serving under him. Ratar-O’s greatest supporter would appear to be Vultureman, who served loyally with Ratar-O on more than one occasion, co-piloting the Mutant commander’s signature vehicle, known as the Rat*Star.", favorite: false, afiliation: mutants)

@luna = Character.create(name: "Luna", gender: "female", weapons: "Queen Luna's Belt and Riding Crop", species: "Lunataks", overview: "Leader of the Lunataks despite her small stature, Luna commands the group by birthright and, at times, by sheer force of will! Cunning, evil and cruel, Luna’s ability to devise inventive and sometimes detailed schemes is hampered only by the ambitions of her fellow Lunataks, and the dissention that is bread within the Lunatak ranks by her authoritative style of leadership.", favorite: false, afiliation: lunataks)

@amok = Character.create(name: "Amok", gender: "male", weapons: "None", species: "Lunataks", overview: "By far the least intelligent of the Lunataks, Amok is the lumbering right-hand creature of Luna, granted the unenviable task of carrying the Lunataks’ leader upon his back wherever he goes. Whilst Amok can be aggressive, his almost childlike nature causes him to lack the pure evil streak that exists within the other Lunataks, and as such Amok is quite loyal to Luna. However, what Amok lacks in intellect or killer instinct he makes up for in brute force, force that is always at the disposal of Luna and the other Lunataks.", favorite: false, afiliation: lunataks)

@aluro = Character.create(name: "Aluro", gender: "male", weapons: "Psyche Club", species: "Lunataks", overview: "An almost sinister figure, Aluro is as dangerous as he is softly spoken. Shunning physical combat in favour of exploiting the weaknesses of his opponents’ minds, Aluro is able to use his persuasive vocal tones to enhance the mind-controlling power of his Psyche Club and leave his victims totally mesmerised, entranced, cowering or demoralised. Despite his understated demeanour, Aluro’s evil nature is boundless, and the Lunatak takes great delight in the mental cruelty he is able to inflict on his enemies. However, like many of his ilk, Aluro’s courage is only as strong as his ability to control his enemies, a weakness that the ThunderCats gratefully exploit!", favorite: false, afiliation: lunataks)

@red_eye = Character.create(name: "Red-Eye", gender: "male", weapons: "Chest Missiles", species: "Lunataks", overview: "A gargantuan figure, Red-Eye is very much the brute force of the Lunataks, both in terms of physical strength and bulk, and also in terms of aggression and firepower. A combatant who relishes physical conflict, Red-Eye regularly plays a central role in the Lunataks’ onslaughts against their enemies, and as such has established himself as one of the ThunderCats’ deadliest foes.", favorite: false, afiliation: lunataks)

@tug_mug = Character.create(name: "Tug-Mug", gender: "male", weapons: "Gravity Carbine", species: "Lunataks", overview: "Along with Red-Eye, Tug Mug’s ability to speedily traverse great distances and subdue his enemies by manipulating the gravity around them has marked him out as one of the central figures of the Lunataks, particularly in combat situations. Like all the Lunataks, Tug Mug is a merciless and formidable adversary, and one that the ThunderCats must defeat if Third Earth is to live in peace.", favorite: false, afiliation: lunataks)

@chilla = Character.create(name: "Chilla", gender: "female", weapons: "Create and manipualte ice", species: "Lunataks", overview: "The mixture of an ice-cold heart and red-hot sensuality, Chilla is cool, cruel and calculating, and always willing to call upon her icy powers to further the Lunatak cause. Beneath her beauty, Chilla cares for no one but herself and leaves a trail of frozen and frostbitten victims in her wake. Despite her slender frame, Chilla’s icy abilities make her one of the most potentially lethal of the ThunderCats’ enemies, an enemy that they will never underestimate.", favorite: false, afiliation: lunataks)
